before_install:
  - sudo apt-get install -y gobject-introspection libgirepository1.0-dev
language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script: true
