before_install:
  - sudo apt-get install -y gobject-introspection libgirepository1.0-dev python-gi python-cairo python-yaml
language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: true
