services:
  ubuntupy:
    image: ubuntupy
    build:
      context: docker
      dockerfile: Dockerfile.ubuntu
      args:
        DEBIAN_FRONTEND: noninteractive
        TZ: Europe/Rome
    volumes:
      - type: bind
        source: $PWD/dist
        target: /opt/dist
        read_only: true
      - type: bind
        source: $PWD/.test-otp.yml
        target: /home/testuser/otp.yml
        read_only: true
  archpy:
    image: archpy
    build:
      context: docker
      dockerfile: Dockerfile.archlinux
      args:
        TZ: Europe/Rome
    environment:
      DISPLAY: ":0.0"
    volumes:
      - type: bind
        source: $PWD/dist
        target: /opt/dist
        read_only: true
      - type: bind
        source: $PWD/.test-otp.yml
        target: /home/testuser/otp.yml
        read_only: true
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
      - type: bind
        source: $HOME/.Xauthority
        target: /home/testuser/.Xauthority
        read_only: false
      - type: bind
        source: $PWD/archpkg
        target: /home/testuser/archpkg
        read_only: true
      - type: bind
        source: $PWD/archbuild
        target: /home/testuser/build
        read_only: false
